// ActionCable-shaped live delivery smoke test. Run after cargo build.
import net from 'node:net';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync, spawn } from 'node:child_process';
import assert from 'node:assert/strict';

const listener=net.createServer();await new Promise(resolve=>listener.listen(0,'127.0.0.1',resolve));const port=listener.address().port;await new Promise(resolve=>listener.close(resolve));
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'rustfire-ws-'));
const child=spawn('target/debug/rustfire',[],{env:{...process.env,RUSTFIRE_ADDR:`127.0.0.1:${port}`,RUSTFIRE_DB:path.join(temp,'test.db'),RUSTFIRE_UPLOAD_DIR:path.join(temp,'uploads'),RUSTFIRE_CAMPFIRE_SECRET_KEY_BASE:'test-secret-key-base'},stdio:'ignore'});
const base=`http://127.0.0.1:${port}`;
try{
  let ready=false;for(let i=0;i<100;i++){try{ready=(await fetch(base+'/up')).ok;if(ready)break}catch{}await new Promise(r=>setTimeout(r,50))}assert(ready,'server started');
  const setupPage=await fetch(base+'/first_run');
  const setupCookie=setupPage.headers.get('set-cookie').split(';')[0];
  const setupCsrf=(await setupPage.text()).match(/<meta name='csrf-token' content='([^']+)'/)[1];
  const setup=await fetch(base+'/first_run',{method:'POST',headers:{Cookie:setupCookie,'X-CSRF-Token':setupCsrf,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({name:'Socket',email_address:'socket@example.com',password:'socketpass123'}),redirect:'manual'});
  assert.equal(setup.status,303);const cookie=setup.headers.get('set-cookie').split(';')[0];
  const csrfPage=await fetch(base+'/rooms/1',{headers:{Cookie:cookie}});
  const roomHtml=await csrfPage.text();
  const csrf=roomHtml.match(/<meta name='csrf-token' content='([^']+)'/)[1];
  const streamToken='IloybGtPaTh2WTJGdGNHWnBjbVV2VW05dmJYTTZPazl3Wlc0dk1ROm1lc3NhZ2VzIg==--dcc17cfeecb1f593debdd6f13d526df3c6d3b2fe59ab972a8fe1e7c038384efd';
  const signedStream=(kind,id)=>{const gid=Buffer.from(`gid://campfire/${kind}/${id}`).toString('base64url');const encoded=Buffer.from(JSON.stringify(`${gid}:messages`)).toString('base64');const key=crypto.pbkdf2Sync('test-secret-key-base','turbo/signed_stream_verifier_key',1000,64,'sha256');return `${encoded}--${crypto.createHmac('sha256',key).update(encoded).digest('hex')}`;};
  assert.equal(signedStream('Rooms::Open',1),streamToken);
  assert(roomHtml.includes(`signed-stream-name='${streamToken}'`));
  const deniedOrigin=await new Promise((resolve,reject)=>{const probe=net.createConnection({host:'127.0.0.1',port});probe.on('connect',()=>probe.write(`GET /cable HTTP/1.1\r\nHost: 127.0.0.1:${port}\r\nOrigin: https://evil.example\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: ${crypto.randomBytes(16).toString('base64')}\r\nCookie: ${cookie}\r\n\r\n`));probe.once('data',data=>{resolve(data.toString().split('\r\n')[0]);probe.destroy()});probe.once('error',reject)});
  assert.match(deniedOrigin,/403/);
  const socket=net.createConnection({host:'127.0.0.1',port});
  const frames=[];let handshake=false;let buffer=Buffer.alloc(0);let resolveFrame;let rejectFrame;let pingCount=0;
  const nextRawFrame=()=>new Promise((resolve,reject)=>{if(frames.length)resolve(frames.shift());else{resolveFrame=resolve;rejectFrame=reject;}});
  const nextFrame=async()=>{for(;;){const frame=await nextRawFrame();if(frame.type!=='ping')return frame;}};
  socket.on('data',chunk=>{
    buffer=Buffer.concat([buffer,chunk]);if(!handshake){const end=buffer.indexOf('\r\n\r\n');if(end<0)return;const head=buffer.subarray(0,end).toString();assert(head.startsWith('HTTP/1.1 101'),head);buffer=buffer.subarray(end+4);handshake=true;}
    while(buffer.length>=2){let length=buffer[1]&127;let offset=2;if(length===126){if(buffer.length<4)return;length=buffer.readUInt16BE(2);offset=4}else if(length===127){if(buffer.length<10)return;length=Number(buffer.readBigUInt64BE(2));offset=10}if(buffer.length<offset+length)return;const opcode=buffer[0]&15;const payload=buffer.subarray(offset,offset+length).toString();buffer=buffer.subarray(offset+length);if(opcode===1){const value=JSON.parse(payload);if(value.type==='ping'){assert.equal(typeof value.message,'number');pingCount++;}if(resolveFrame){resolveFrame(value);resolveFrame=null}else frames.push(value)}}
  });
  socket.on('error',e=>{if(rejectFrame)rejectFrame(e)});
  const key=crypto.randomBytes(16).toString('base64');socket.write(`GET /cable HTTP/1.1\r\nHost: 127.0.0.1:${port}\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: ${key}\r\nSec-WebSocket-Protocol: actioncable-v1-json\r\nCookie: ${cookie}\r\n\r\n`);
  const welcome=await nextFrame();assert.equal(welcome.type,'welcome');
  const sendCommand=command=>{const payload=Buffer.from(JSON.stringify(command));const length=payload.length;assert(length<65536);const long=length>=126;const maskOffset=long?4:2;const packet=Buffer.alloc(maskOffset+4+length);packet[0]=0x81;packet[1]=0x80|(long?126:length);if(long)packet.writeUInt16BE(length,2);const mask=crypto.randomBytes(4);mask.copy(packet,maskOffset);for(let i=0;i<length;i++)packet[maskOffset+4+i]=payload[i]^mask[i%4];socket.write(packet);};
  const identifier=JSON.stringify({channel:'RoomMessagesChannel',room_id:1});
  sendCommand({command:'subscribe',identifier});
  const confirmation=await nextFrame();assert.equal(confirmation.type,'confirm_subscription');
  const signedIdentifier=JSON.stringify({channel:'RoomMessagesChannel',signed_stream_name:streamToken});
  sendCommand({command:'subscribe',identifier:signedIdentifier});
  assert.equal((await nextFrame()).type,'confirm_subscription');
  sendCommand({command:'subscribe',identifier:JSON.stringify({channel:'RoomMessagesChannel',signed_stream_name:streamToken+'x'})});
  assert.equal((await nextFrame()).type,'reject_subscription');
  sendCommand({command:'subscribe',identifier:JSON.stringify({channel:'RoomMessagesChannel',signed_stream_name:signedStream('Rooms::Closed',1)})});
  assert.equal((await nextFrame()).type,'reject_subscription');
  sendCommand({command:'subscribe',identifier:JSON.stringify({channel:'RoomMessagesChannel',signed_stream_name:signedStream('Rooms::Open',999)})});
  assert.equal((await nextFrame()).type,'reject_subscription');
  const heartbeatIdentifier=JSON.stringify({channel:'HeartbeatChannel'});
  sendCommand({command:'subscribe',identifier:heartbeatIdentifier});
  assert.equal((await nextFrame()).type,'confirm_subscription');
  const listSources=[...roomHtml.matchAll(/<turbo-cable-stream-source channel='Turbo::StreamsChannel' signed-stream-name='([^']+)'/g)].map(match=>match[1]);
  assert.equal(listSources.length,2);
  const globalListIdentifier=JSON.stringify({channel:'Turbo::StreamsChannel',signed_stream_name:listSources[0]});
  const userListIdentifier=JSON.stringify({channel:'Turbo::StreamsChannel',signed_stream_name:listSources[1]});
  sendCommand({command:'subscribe',identifier:globalListIdentifier});
  assert.equal((await nextFrame()).type,'confirm_subscription');
  sendCommand({command:'subscribe',identifier:userListIdentifier});
  assert.equal((await nextFrame()).type,'confirm_subscription');
  sendCommand({command:'subscribe',identifier:JSON.stringify({channel:'Turbo::StreamsChannel',signed_stream_name:streamToken})});
  assert.equal((await nextFrame()).type,'reject_subscription');
  const otherUserGid=Buffer.from('gid://campfire/User/2').toString('base64url');
  const otherUserName=Buffer.from(JSON.stringify(`${otherUserGid}:rooms`)).toString('base64');
  const streamKey=crypto.pbkdf2Sync('test-secret-key-base','turbo/signed_stream_verifier_key',1000,64,'sha256');
  const otherUserToken=`${otherUserName}--${crypto.createHmac('sha256',streamKey).update(otherUserName).digest('hex')}`;
  sendCommand({command:'subscribe',identifier:JSON.stringify({channel:'Turbo::StreamsChannel',signed_stream_name:otherUserToken})});
  assert.equal((await nextFrame()).type,'reject_subscription');
  const setInvolvement=async value=>{
    const response=await fetch(base+'/rooms/1/involvement',{method:'PUT',headers:{Cookie:cookie,'Content-Type':'application/x-www-form-urlencoded','X-CSRF-Token':csrf},body:new URLSearchParams({involvement:value}),redirect:'manual'});
    assert.equal(response.status,302);
  };
  await setInvolvement('invisible');
  const hiddenEvent=await nextFrame();
  assert.equal(hiddenEvent.identifier,userListIdentifier);
  assert.equal(hiddenEvent.message,'<turbo-stream action="remove" target="list_rooms_open_1"></turbo-stream>');
  await setInvolvement('everything');
  const visibleEvent=await nextFrame();
  assert.equal(visibleEvent.identifier,userListIdentifier);
  assert.match(visibleEvent.message,/^<turbo-stream action="prepend" target="shared_rooms"><template><a id='list_rooms_open_1'/);
  sendCommand({command:'unsubscribe',identifier:globalListIdentifier});
  sendCommand({command:'unsubscribe',identifier:userListIdentifier});
  const streamClientId='ws-stream-1';
  const streamPost=await fetch(base+'/rooms/1/messages',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json','X-CSRF-Token':csrf},body:new URLSearchParams({'message[body]':'signed stream test','message[client_message_id]':streamClientId})});
  assert.equal(streamPost.status,201);
  const streamMessageId=(await streamPost.json()).id;
  const streamEvents=[await nextFrame(),await nextFrame()];
  assert(streamEvents.some(frame=>frame.identifier===identifier&&frame.message?.message?.body?.plain_text==='signed stream test'));
  assert(streamEvents.some(frame=>frame.identifier===signedIdentifier&&typeof frame.message==='string'&&frame.message.includes('<turbo-stream action="append" target="messages_rooms_open_1">')&&frame.message.includes(`id='message_${streamClientId}' class='message '`)&&frame.message.includes(`data-message-id='${streamMessageId}'`)&&frame.message.includes("<h2 class='message__day-separator'><time")&&frame.message.includes("data-local-time-target='date'")&&frame.message.includes("src='/users/eyJ")&&frame.message.includes(`<turbo-frame id='edit_message_${streamClientId}'>`)&&frame.message.includes(`<turbo-frame id='boosting_message_${streamClientId}'>`)&&frame.message.includes(`<turbo-frame id='new_boost_message_${streamClientId}'>`)&&frame.message.includes(`data-turbo-frame='boosting_message_${streamClientId}'`)&&frame.message.includes(`href='/messages/${streamMessageId}/boosts/new'`)&&frame.message.includes('signed stream test')));
  const messageStream=streamEvents.find(frame=>frame.identifier===signedIdentifier).message;
  assert.match(messageStream,/<div class='message__meta'><h3 class='message__heading'>[\s\S]*?<\/h3><div class='message__actions'/);
  assert(messageStream.includes(`data-copy-to-clipboard-content-value='${base}/rooms/1/@${streamMessageId}'`));
  assert(!messageStream.includes('custom-boost-form'));
  assert(!messageStream.includes('data-stream-message'));
  assert(!messageStream.includes('data-creator-id'));
  assert(!messageStream.includes('data-local-datetime'));
  const streamEdit=await fetch(base+`/rooms/1/messages/${streamMessageId}`,{method:'PATCH',headers:{Cookie:cookie,'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json','X-CSRF-Token':csrf},body:new URLSearchParams({'message[body]':'signed stream edited'})});
  assert.equal(streamEdit.status,200);
  const editEvents=[await nextFrame(),await nextFrame()];
  assert(editEvents.some(frame=>frame.identifier===signedIdentifier&&typeof frame.message==='string'&&frame.message.includes(`<turbo-stream action="replace" target="presentation_message_${streamClientId}">`)&&frame.message.includes('signed stream edited')));
  const streamBoost=await fetch(base+`/messages/${streamMessageId}/boosts`,{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/x-www-form-urlencoded','X-CSRF-Token':csrf},body:new URLSearchParams({content:'🔥'}),redirect:'manual'});
  assert.equal(streamBoost.status,303);
  const boostEvents=[await nextFrame(),await nextFrame()];
  const streamBoostId=Number(execFileSync('python',['-c','import sqlite3,sys;print(sqlite3.connect(sys.argv[1]).execute("select max(id) from boosts").fetchone()[0])',path.join(temp,'test.db')]).toString().trim());
  assert(boostEvents.some(frame=>frame.identifier===signedIdentifier&&typeof frame.message==='string'&&frame.message.includes(`<turbo-stream maintain_scroll="true" action="append" target="boosts_message_${streamClientId}">`)&&frame.message.includes(`id='boost_${streamBoostId}'`)&&frame.message.includes("aria-label='Socket boosted 🔥'")&&frame.message.includes("class='txt-small txt-medium'")&&frame.message.includes("data-boost-delete-target='button'")));
  const roomWithBoost=await (await fetch(base+'/rooms/1',{headers:{Cookie:cookie}})).text();
  assert(roomWithBoost.includes(`id='boost_${streamBoostId}'`)&&roomWithBoost.includes("aria-label='Socket boosted 🔥'")&&roomWithBoost.includes("class='txt-small txt-medium'")&&roomWithBoost.includes("data-boost-delete-target='button'"));
  const streamBoostDelete=await fetch(base+`/messages/${streamMessageId}/boosts/${streamBoostId}`,{method:'DELETE',headers:{Cookie:cookie,'X-CSRF-Token':csrf,Accept:'text/vnd.turbo-stream.html'},redirect:'manual'});
  assert.equal(streamBoostDelete.status,200);
  const boostDeleteEvents=[await nextFrame(),await nextFrame()];
  assert(boostDeleteEvents.some(frame=>frame.identifier===signedIdentifier&&frame.message===`<turbo-stream action="remove" target="boost_${streamBoostId}"></turbo-stream>`));
  const streamDelete=await fetch(base+`/rooms/1/messages/${streamMessageId}`,{method:'DELETE',headers:{Cookie:cookie,Accept:'text/vnd.turbo-stream.html','X-CSRF-Token':csrf},redirect:'manual'});
  assert.equal(streamDelete.status,200);
  const deleteEvents=[await nextFrame(),await nextFrame()];
  assert(deleteEvents.some(frame=>frame.identifier===signedIdentifier&&frame.message===`<turbo-stream action="remove" target="message_${streamClientId}"></turbo-stream>`));
  sendCommand({command:'unsubscribe',identifier:signedIdentifier});
  sendCommand({command:'unsubscribe',identifier:heartbeatIdentifier});
  const typingIdentifier=JSON.stringify({channel:'TypingNotificationsChannel',room_id:1});
  sendCommand({command:'subscribe',identifier:typingIdentifier});
  assert.equal((await nextFrame()).type,'confirm_subscription');
  sendCommand({command:'subscribe',identifier:JSON.stringify({channel:'TypingNotificationsChannel',room_id:999})});
  assert.equal((await nextFrame()).type,'reject_subscription');
  sendCommand({command:'message',identifier:typingIdentifier,data:JSON.stringify({action:'start'})});
  const typing=await nextFrame();assert.equal(typing.identifier,typingIdentifier);assert.equal(typing.message.action,'start');assert.equal(typing.message.user.name,'Socket');
  sendCommand({command:'message',identifier:typingIdentifier,data:JSON.stringify({action:'stop'})});
  assert.equal((await nextFrame()).message.action,'stop');
  const presenceIdentifier=JSON.stringify({channel:'PresenceChannel',room_id:1});
  sendCommand({command:'subscribe',identifier:presenceIdentifier});
  assert.equal((await nextFrame()).type,'confirm_subscription');
  const connections=()=>Number(execFileSync('python',['-c','import sqlite3,sys;print(sqlite3.connect(sys.argv[1]).execute("select connections from memberships where room_id=1 and user_id=1").fetchone()[0])',path.join(temp,'test.db')]).toString().trim());
  for(let i=0;i<30&&connections()!==1;i++)await new Promise(r=>setTimeout(r,20));
  assert.equal(connections(),1);
  sendCommand({command:'message',identifier:presenceIdentifier,data:JSON.stringify({action:'absent'})});
  for(let i=0;i<30&&connections()!==0;i++)await new Promise(r=>setTimeout(r,20));
  assert.equal(connections(),0);
  sendCommand({command:'message',identifier:presenceIdentifier,data:JSON.stringify({action:'present'})});
  for(let i=0;i<30&&connections()!==1;i++)await new Promise(r=>setTimeout(r,20));
  assert.equal(connections(),1);
  const unreadIdentifier=JSON.stringify({channel:'UnreadRoomsChannel'});
  const readIdentifier=JSON.stringify({channel:'ReadRoomsChannel'});
  sendCommand({command:'subscribe',identifier:unreadIdentifier});assert.equal((await nextFrame()).type,'confirm_subscription');
  sendCommand({command:'subscribe',identifier:readIdentifier});assert.equal((await nextFrame()).type,'confirm_subscription');
  sendCommand({command:'message',identifier:presenceIdentifier,data:JSON.stringify({action:'absent'})});
  for(let i=0;i<30&&connections()!==0;i++)await new Promise(r=>setTimeout(r,20));
  assert.equal(connections(),0);
  const joinCode=execFileSync('python',['-c','import sqlite3,sys;print(sqlite3.connect(sys.argv[1]).execute("select join_code from accounts limit 1").fetchone()[0])',path.join(temp,'test.db')]).toString().trim();
  const joinPage=await fetch(base+'/join/'+joinCode);
  const joinCookie=joinPage.headers.get('set-cookie').split(';')[0];
  const joinCsrf=(await joinPage.text()).match(/<meta name='csrf-token' content='([^']+)'/)[1];
  const joined=await fetch(base+'/join/'+joinCode,{method:'POST',headers:{Cookie:joinCookie,'X-CSRF-Token':joinCsrf,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({name:'Other',email_address:'other@example.com',password:'otherpass123'}),redirect:'manual'});
  assert.equal(joined.status,303);const otherCookie=joined.headers.get('set-cookie').split(';')[0];
  const otherPage=await fetch(base+'/rooms/1',{headers:{Cookie:otherCookie}});
  const otherCsrf=(await otherPage.text()).match(/<meta name='csrf-token' content='([^']+)'/)[1];
  const otherPost=await fetch(base+'/rooms/1/messages',{method:'POST',headers:{Cookie:otherCookie,'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json','X-CSRF-Token':otherCsrf},body:new URLSearchParams({'message[body]':'from other','message[client_message_id]':'ws-other'})});assert.equal(otherPost.status,201);
  const updates=[await nextFrame(),await nextFrame()];
  assert(updates.some(frame=>frame.identifier===unreadIdentifier&&frame.message.roomId===1));
  assert(updates.some(frame=>frame.identifier===identifier&&frame.message.message.body.plain_text==='from other'));
  const readRoom=await fetch(base+'/rooms/1',{headers:{Cookie:cookie}});assert.equal(readRoom.status,200);
  const readUpdate=await nextFrame();assert.equal(readUpdate.identifier,readIdentifier);assert.equal(readUpdate.message.room_id,1);
  sendCommand({command:'message',identifier:presenceIdentifier,data:JSON.stringify({action:'present'})});
  for(let i=0;i<30&&connections()!==1;i++)await new Promise(r=>setTimeout(r,20));
  assert.equal(connections(),1);
  const post=await fetch(base+'/rooms/1/messages',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json','X-CSRF-Token':csrf},body:new URLSearchParams({'message[body]':'live test','message[client_message_id]':'ws-1'})});assert.equal(post.status,201);
  let delivered;
  for(let i=0;i<5;i++){const frame=await Promise.race([nextFrame(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('no room event')),3000))]);if(frame.identifier===identifier&&frame.message?.message?.body?.plain_text==='live test'){delivered=frame;break;}}
  assert(delivered,'live message delivered');
  const created=await post.json();
  const boost=await fetch(base+`/messages/${created.id}/boosts`,{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/x-www-form-urlencoded','X-CSRF-Token':csrf},body:new URLSearchParams({content:'🔥'}),redirect:'manual'});assert.equal(boost.status,303);
  let boosted;
  for(let i=0;i<5;i++){const frame=await Promise.race([nextFrame(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('no boost event')),3000))]);if(frame.identifier===identifier&&frame.message?.type==='boost'){boosted=frame;break;}}
  assert(boosted&&boosted.message.room_id===1&&boosted.message.message_id===created.id&&boosted.message.content==='🔥','room boost delivered');
  const boostId=Number(execFileSync('python',['-c','import sqlite3,sys;print(sqlite3.connect(sys.argv[1]).execute("select max(id) from boosts").fetchone()[0])',path.join(temp,'test.db')]).toString().trim());
  const removed=await fetch(base+`/messages/${created.id}/boosts/${boostId}`,{method:'DELETE',headers:{Cookie:cookie,'X-CSRF-Token':csrf,Accept:'text/vnd.turbo-stream.html'},redirect:'manual'});assert.equal(removed.status,200);
  let deletion;
  for(let i=0;i<5;i++){const frame=await Promise.race([nextFrame(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('no boost removal event')),3000))]);if(frame.identifier===identifier&&frame.message?.type==='boost_deleted'){deletion=frame;break;}}
  assert(deletion&&deletion.message.room_id===1&&deletion.message.id===boostId&&deletion.message.content==='🔥','room boost removal delivered');
  const roomListIdentifier=JSON.stringify({channel:'RoomListChannel'});
  sendCommand({command:'subscribe',identifier:roomListIdentifier});
  assert.equal((await nextFrame()).type,'confirm_subscription');
  for(const involvement of ['invisible','mentions']){
    const changed=await fetch(base+'/rooms/1/involvement',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/x-www-form-urlencoded','X-CSRF-Token':csrf},body:new URLSearchParams({involvement}),redirect:'manual'});
    assert.equal(changed.status,302);
    assert.equal(new URL(changed.headers.get('location'),base).pathname,'/rooms/1/involvement');
    const frame=await Promise.race([nextFrame(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('no visibility event')),3000))]);
    assert.equal(frame.identifier,roomListIdentifier);
    assert.equal(frame.message.type,'rooms_changed');
    const sidebar=await fetch(base+'/users/me/sidebar?active=1',{headers:{Cookie:cookie}});
    assert.equal(sidebar.headers.get('x-rustfire-active-room-accessible'),'1');
    assert.equal((await sidebar.text()).includes("href='/rooms/1'"),involvement!=='invisible');
  }
  sendCommand({command:'subscribe',identifier:globalListIdentifier});
  assert.equal((await nextFrame()).type,'confirm_subscription');
  sendCommand({command:'subscribe',identifier:userListIdentifier});
  assert.equal((await nextFrame()).type,'confirm_subscription');
  const privateRoom=await fetch(base+'/rooms/closeds',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/x-www-form-urlencoded','X-CSRF-Token':csrf},body:new URLSearchParams([['room[name]','Private socket room'],['user_ids[]','1'],['user_ids[]','2']]),redirect:'manual'});
  assert.equal(privateRoom.status,303);
  const privateRoomId=Number(privateRoom.headers.get('location').match(/\/rooms\/(\d+)/)[1]);
  const createdEvents=[await nextFrame(),await nextFrame()];
  assert(createdEvents.some(event=>event.identifier===roomListIdentifier&&event.message.type==='rooms_changed'));
  assert(createdEvents.some(event=>event.identifier===userListIdentifier&&event.message.includes(`action="prepend" target="shared_rooms"`)&&event.message.includes(`id='list_rooms_closed_${privateRoomId}'`)));
  const sidebarAfterCreate=await fetch(base+'/users/me/sidebar?active=1',{headers:{Cookie:cookie}});
  assert.equal(sidebarAfterCreate.status,200);
  assert.match(await sidebarAfterCreate.text(),new RegExp(`href='/rooms/${privateRoomId}'`));
  const otherSocket=net.createConnection({host:'127.0.0.1',port});
  const otherReady=new Promise((resolve,reject)=>{otherSocket.once('error',reject);otherSocket.once('data',data=>data.toString().startsWith('HTTP/1.1 101')?resolve():reject(new Error('other socket handshake failed')))});
  otherSocket.on('connect',()=>otherSocket.write(`GET /cable HTTP/1.1\r\nHost: 127.0.0.1:${port}\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: ${crypto.randomBytes(16).toString('base64')}\r\nSec-WebSocket-Protocol: actioncable-v1-json\r\nCookie: ${otherCookie}\r\n\r\n`));
  await otherReady;
  const otherClosed=new Promise(resolve=>otherSocket.once('close',resolve));
  const revoke=await fetch(base+`/rooms/closeds/${privateRoomId}`,{method:'PATCH',headers:{Cookie:cookie,'Content-Type':'application/x-www-form-urlencoded','X-CSRF-Token':csrf},body:new URLSearchParams([['room[name]','Private socket room'],['user_ids[]','1']]),redirect:'manual'});
  assert.equal(revoke.status,303);
  const updatedEvents=[await nextFrame(),await nextFrame()];
  assert(updatedEvents.some(event=>event.identifier===roomListIdentifier&&event.message.type==='rooms_changed'));
  assert(updatedEvents.some(event=>event.identifier===userListIdentifier&&event.message.includes(`action="replace" target="list_rooms_closed_${privateRoomId}"`)));
  const deleteRoom=await fetch(base+`/rooms/closeds/${privateRoomId}`,{method:'DELETE',headers:{Cookie:cookie,'X-CSRF-Token':csrf},redirect:'manual'});
  assert.equal(deleteRoom.status,303);
  const deletedEvents=[await nextFrame(),await nextFrame()];
  assert(deletedEvents.some(event=>event.identifier===roomListIdentifier&&event.message.type==='rooms_changed'));
  assert(deletedEvents.some(event=>event.identifier===globalListIdentifier&&event.message===`<turbo-stream action="remove" target="list_rooms_closed_${privateRoomId}"></turbo-stream>`));
  sendCommand({command:'unsubscribe',identifier:globalListIdentifier});
  sendCommand({command:'unsubscribe',identifier:userListIdentifier});
  const sidebarAfterDelete=await fetch(base+'/users/me/sidebar?active=1',{headers:{Cookie:cookie}});
  assert.equal(sidebarAfterDelete.status,200);
  assert.doesNotMatch(await sidebarAfterDelete.text(),new RegExp(`href='/rooms/${privateRoomId}'`));
  await Promise.race([otherClosed,new Promise((_,reject)=>setTimeout(()=>reject(new Error('revoked member socket remained open')),3000))]);
  let directId;
  for(let attempt=0;attempt<2;attempt++){
    const direct=await fetch(base+'/rooms/directs',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/x-www-form-urlencoded','X-CSRF-Token':csrf},body:new URLSearchParams({'user_ids[]':'2'}),redirect:'manual'});
    assert.equal(direct.status,302);
    const id=Number(direct.headers.get('location').match(/\/rooms\/(\d+)/)[1]);
    if(directId)assert.equal(id,directId);else directId=id;
    const event=await Promise.race([nextFrame(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('no direct room event')),3000))]);
    assert.equal(event.identifier,roomListIdentifier);
    assert.equal(event.message.type,'direct_room_added');
    assert.equal(event.message.room_id,directId);
    assert.match(event.message.html,new RegExp(`href='/rooms/${directId}'`));
  }
  const directSidebar=await fetch(base+'/users/me/sidebar?active=1',{headers:{Cookie:cookie}});
  assert.match(await directSidebar.text(),new RegExp(`href='/rooms/${directId}'`));
  const ignoredId=await fetch(base+'/rooms/directs',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/x-www-form-urlencoded','X-CSRF-Token':csrf},body:new URLSearchParams([['user_ids[]','2'],['user_ids[]','999999']]),redirect:'manual'});
  assert.equal(ignoredId.status,302);
  assert.equal(ignoredId.headers.get('location'),`/rooms/${directId}`);
  assert.equal((await nextFrame()).message.room_id,directId);
  const selfPing=await fetch(base+'/rooms/directs',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/x-www-form-urlencoded','X-CSRF-Token':csrf},body:new URLSearchParams(),redirect:'manual'});
  assert.equal(selfPing.status,302);
  const selfId=Number(selfPing.headers.get('location').match(/\/rooms\/(\d+)/)[1]);
  assert.notEqual(selfId,directId);
  assert.equal((await nextFrame()).message.room_id,selfId);
  const deactivationSocket=net.createConnection({host:'127.0.0.1',port});
  const deactivationReady=new Promise((resolve,reject)=>{deactivationSocket.once('error',reject);deactivationSocket.once('data',data=>data.toString().startsWith('HTTP/1.1 101')?resolve():reject(new Error('deactivation socket handshake failed')))});
  deactivationSocket.on('connect',()=>deactivationSocket.write(`GET /cable HTTP/1.1\r\nHost: 127.0.0.1:${port}\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: ${crypto.randomBytes(16).toString('base64')}\r\nSec-WebSocket-Protocol: actioncable-v1-json\r\nCookie: ${otherCookie}\r\n\r\n`));
  await deactivationReady;
  const deactivatedClosed=new Promise(resolve=>deactivationSocket.once('close',resolve));
  const deactivate=await fetch(base+'/account/users/2',{method:'DELETE',headers:{Cookie:cookie,'X-CSRF-Token':csrf},redirect:'manual'});
  assert.equal(deactivate.status,302);
  assert.equal(new URL(deactivate.headers.get('location'),base).pathname,'/account/edit');
  await Promise.race([deactivatedClosed,new Promise((_,reject)=>setTimeout(()=>reject(new Error('deactivated user socket remained open')),3000))]);
  for(let i=0;i<80&&pingCount===0;i++)await new Promise(r=>setTimeout(r,50));
  assert(pingCount>0,'ActionCable heartbeat delivered');
  const closed=new Promise(resolve=>socket.once('close',resolve));
  const signout=await fetch(base+'/session',{method:'DELETE',headers:{Cookie:cookie,'X-CSRF-Token':csrf},redirect:'manual'});assert.equal(signout.status,303);
  await Promise.race([closed,new Promise((_,reject)=>setTimeout(()=>reject(new Error('socket remained open after sign out')),3000))]);
  for(let i=0;i<30&&connections()!==0;i++)await new Promise(r=>setTimeout(r,20));
  assert.equal(connections(),0);
  console.log('PASS websocket welcome, subscriptions, typing, presence, live message and boost changes, room list updates, membership, deactivation, and sign-out revocation');
}finally{child.kill('SIGTERM');fs.rmSync(temp,{recursive:true,force:true})}
